name: Deployment For Studio

on:
  push:
    branches:
      cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.STUDIO_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.STUDIO_SERVER_USERNAME }}
          TARGET: "/home/ubuntu/mono-portal-api"

      - name: Execute pm2 after every deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STUDIO_SERVER_HOST }}
          username: ${{ secrets.STUDIO_SERVER_USERNAME }}
          key: ${{ secrets.STUDIO_KEY }}
          port: "22"
          script: |
            cd mono-portal-api
            git pull
            #export NVM_DIR=~/.nvm
            #source ~/.nvm/nvm.sh
            npm i
            npm run build
            cd ~
            pm2 restart ecosystem.config.js --only mono-home --env production
