name: Deployment For Studio

on:
  push:
    branches:
      cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STUDIO_SERVER_HOST }}
          username: ${{ secrets.STUDIO_SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.STUDIO_KEY }}
          script: |
            cd ~
            pm2 start && pm2 restart ecosystem.config.js --only mono-portal-api
