name: Integration Testing For Studio

on:
  push:
    branches:
      cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install modules
        run: npm install

      - name: build artifacts
        run: npm run build
