name: Deployment For Studio

on:
  push:
    branches:
      cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "3.132.218.48"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/api"
          EXCLUDE: "/.git/, /.github/"

      - name: Execute
        uses: appleboy/ssh-action@master
        with:
          host: "3.132.218.48"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          port: "22"
          script: |
            cd ~
            pm2 start && pm2 restart ecosystem.config.js --only mono-portal-api
